// Code generated by "stringer -type=DataType"; DO NOT EDIT.

package recipe

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Column-0]
	_ = x[Variable-1]
	_ = x[Literal-2]
	_ = x[Placeholder-3]
	_ = x[Header-4]
}

const _DataType_name = "ColumnVariableLiteralPlaceholderHeader"

var _DataType_index = [...]uint8{0, 6, 14, 21, 32, 38}

func (i DataType) String() string {
	if i < 0 || i >= DataType(len(_DataType_index)-1) {
		return "DataType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DataType_name[_DataType_index[i]:_DataType_index[i+1]]
}
