// Code generated by "stringer -type=JoinMode"; DO NOT EDIT.

package recipe

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Replace-0]
	_ = x[Join-1]
}

const _JoinMode_name = "ReplaceJoin"

var _JoinMode_index = [...]uint8{0, 7, 11}

func (i JoinMode) String() string {
	if i < 0 || i >= JoinMode(len(_JoinMode_index)-1) {
		return "JoinMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _JoinMode_name[_JoinMode_index[i]:_JoinMode_index[i+1]]
}
